image: python:3-stretch

before_script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r requirements.txt

black:
  script:
    - python3 black --check comission.py comission/

