image: python:3-stretch

before_script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r requirements.txt
  - pip3 install black

black:
  script:
    - black --check --diff comission.py comission/

